# Generated by Django 3.0.4 on 2020-03-20 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('ID', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EMPID', models.CharField(max_length=100, unique=True, verbose_name='Employee ID')),
                ('FIRSTNAME', models.CharField(max_length=100, verbose_name='First Name')),
                ('MIDDLENAME', models.CharField(blank=True, max_length=100, null=True)),
                ('LASTNAME', models.CharField(max_length=100)),
                ('EMAIL', models.EmailField(max_length=50, unique=True)),
                ('GENDER', models.CharField(max_length=20)),
                ('DOJ', models.DateField()),
                ('EMPTYPE', models.CharField(max_length=100)),
                ('STATUS', models.CharField(max_length=100)),
                ('SEATID', models.CharField(blank=True, max_length=100, null=True)),
                ('EXTENSIONNUMBER', models.IntegerField(blank=True, null=True)),
                ('UNIT', models.CharField(blank=True, max_length=100, null=True)),
                ('DEPARTMENT', models.CharField(blank=True, max_length=100, null=True)),
                ('CAREERTRACK', models.CharField(blank=True, max_length=100, null=True)),
                ('DESIGNATION', models.CharField(max_length=100)),
                ('PROJECTS', models.CharField(blank=True, max_length=100, null=True)),
                ('MANAGER', models.CharField(blank=True, max_length=100, null=True)),
                ('BASELOCATION', models.CharField(blank=True, max_length=200, null=True)),
                ('CURRENTLOCATION', models.CharField(blank=True, max_length=200, null=True)),
                ('DOB', models.DateField(blank=True, null=True)),
                ('MOBILENUMBER', models.CharField(max_length=100)),
            ],
        ),
    ]
