# Generated by Django 3.0.4 on 2020-03-20 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='ID',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
