# Generated by Django 3.0.4 on 2020-03-20 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_auto_20200320_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='EMPID',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Employee ID'),
        ),
    ]
